version: '3.9'
services:
  web-server:
    build: ./api_server

    command: uvicorn api_server:app --host 0.0.0.0 --port 5000 --reload

    ports:
      - "5000:5000"

  inference-server:
    build: ./inference_server
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

    ports:
      - "10000:10000"

    command: uvicorn inference_server:app --host 0.0.0.0 --port 10000 --reload
