version: '3.9'
services:
  api-server:
    build: ./api_server
    ports:
      - "5000:5000"
    environment:
      - BUCKET_NAME=s3musicproject
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - REGION_NAME=ap-northeast-2
      - INFERENCE_URL=http://inference-server:10000/inference

  inference-server:
    build: ./inference_server
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
      - "10000:10000"
    environment:
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - REGION_NAME=ap-northeast-2
