version: '3.9'
services:
  api-server:
    build: ./api_server
    ports:
      - "5000:5000"
    environment:
      - BUCKET_NAME=s3musicproject
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - REGION_NAME=ap-northeast-2
      - MONGODB_URI = "mongodb://localhost:27017/"
     

  inference-server:
    build: ./inference_server
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
      mode: replicated
      replicas: 2     

    environment:
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - REGION_NAME=ap-northeast-2
      - MONGODB_URI = "mongodb://localhost:27017/"

  rvc-training-server:
    build: ./rvc_training_server
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

    environment:
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - REGION_NAME=ap-northeast-2
      - MONGODB_URI = "mongodb://localhost:27017/"

  rvc-inference-server:
    build: ./rvc_inference_server
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

    environment:
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - REGION_NAME=ap-northeast-2
      - MONGODB_URI = "mongodb://localhost:27017/"
