version: '3.9'
services:
  api-server:
    build: ./api_server
    ports:
      - "5000:5000"
    environment:
      - BUCKET_NAME=s3musicproject
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - REGION_NAME=ap-northeast-2
      - MONGODB_URI=${MONGODB_URI}
    
    depends_on:
      - mongodb

  inference-server:
    build: ./inference_server
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
      mode: replicated
      replicas: 2     

    environment:
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - REGION_NAME=ap-northeast-2
      - MONGODB_URI=${MONGODB_URI}

    depends_on:
      - mongodb

  rvc-training-server:
    build: ./rvc_training_server
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

    environment:
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - REGION_NAME=ap-northeast-2
      - MONGODB_URI=${MONGODB_URI}

    depends_on:
      - mongodb


  rvc-inference-server:
    build: ./rvc_inference_server
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

    environment:
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - REGION_NAME=ap-northeast-2
      - MONGODB_URI=${MONGODB_URI}
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=1234
  
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=1234
      - ME_CONFIG_MONGODB_URL=mongodb://root:1234@mongodb:27017
      - ME_CONFIG_MONGODB_SERVER=mongodb
volumes:
  mongodb_data: