version: '3.9'
services:
  web-server:
    build: ./web_server
    ports:
      - "5173:5173"

  api-server:
    build: ./api_server
    ports:
      - "5000:5000"
    environment:
      - BUCKET_NAME=s3musicproject
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - REGION_NAME=${REGION_NAME}
      - MONGODB_URI=${MONGODB_URI}
    
    depends_on:
      - mongodb

  inference-server:
    build: ./inference_server
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
      mode: replicated
      replicas: 2     

    environment:
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - REGION_NAME=${REGION_NAME}
      - MONGODB_URI=${MONGODB_URI}

    depends_on:
      - mongodb

  vc-training-server:
    build: ./vc_training_server
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

    environment:
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - REGION_NAME=${REGION_NAME}
      - MONGODB_URI=${MONGODB_URI}

    depends_on:
      - mongodb


  vc-inference-server:
    build: ./vc_inference_server
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

    environment:
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - REGION_NAME=${REGION_NAME}
      - MONGODB_URI=${MONGODB_URI}
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
  
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - ME_CONFIG_MONGODB_URL=${MONGODB_URI}
      - ME_CONFIG_MONGODB_SERVER=mongodb
volumes:
  mongodb_data: